### ISSUE TITLE
TR score

### ISSUE THREAD

**Issue by xiewen354** [gowitheflow-1998/RAR-b#2]
Hi, I would like to know how the TR score in Table 2 of your paper came out and which dataset was used? l1?  l2?  l3?  or mean?

**Comment by gowitheflow-1998** [comment]
@xiewen354 Hi, please see Table 4 (the "avg fair" column)and and Section 4.1 for a detailed explanation of this. Basically, for L2 and L3, I contruct 3 settings (pure, fact and context), and the score in Table 2 is the mean of (L1 + L2 pure + L2 fact + L3 pure + L3 fact), and L2 context and L3 context are excluded for this mean for fair context length comparison. 

Let me know if this helps!

**Comment by xiewen354** [comment]
ok, thanks. 
In addition, I found two possible errors.
1. Line 92 of rarb/evaluation_utils.py, if doc_instruction is None, this results in the following error; site-packages/beir/retrieval/search/dense/exact_search.py", line 47, in <lambda>
corpus_ids = sorted(corpus, key=lambda k: len(corpus[k].get("title", "") + corpus[k].get("text", "")), reverse=True)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
It can be changed to: documents[key]['title'] = doc_instruction if doc_instruction is not None else ""
2. Another possible error is that in the readme Demo, after evaluating without_instruction, the data should be reloaded, because the query and doc may change. For example (evaluate_full_instructor queries[key] = [', queries[key]])

**Comment by gowitheflow-1998** [comment]
@xiewen354 thanks for the discussion!

1. Indeed, because for the InstructOR evaluation, I always passed in a valid doc_instruction (an actual string) and only controlled with the evaluate_with_instruction parameter (when it's false, the doc_instruction is ignored no matter what it is), so I never spotted this bug. Have fixed with your suggestion.

2. Thanks for spotting this. I realized this from the very beginning and actually did reload it in the actual script in the experiment (fortunately).  This shouldn't be a problem for all models except E5-Mistral and Instructor. For Grit for example, the query is modified on the fly instead of changing the content in the query dict. And for all other models, we first evaluate the without-instruction setting so nothing is changed when the with-instruction setting is evaluated. 

I will update the repo with all evaluation scripts soon too. Thanks again.
